//go:build !ignore_autogenerated

/*
Copyright 2020 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/netbirdio/netbird/shared/management/http/api"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountExtraSettings) DeepCopyInto(out *AccountExtraSettings) {
	*out = *in
	if in.NetworkTrafficLogsGroups != nil {
		in, out := &in.NetworkTrafficLogsGroups, &out.NetworkTrafficLogsGroups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountExtraSettings.
func (in *AccountExtraSettings) DeepCopy() *AccountExtraSettings {
	if in == nil {
		return nil
	}
	out := new(AccountExtraSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountSettings) DeepCopyInto(out *AccountSettings) {
	*out = *in
	if in.Extra != nil {
		in, out := &in.Extra, &out.Extra
		*out = new(AccountExtraSettings)
		(*in).DeepCopyInto(*out)
	}
	if in.JwtAllowGroups != nil {
		in, out := &in.JwtAllowGroups, &out.JwtAllowGroups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountSettings.
func (in *AccountSettings) DeepCopy() *AccountSettings {
	if in == nil {
		return nil
	}
	out := new(AccountSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GroupMinimum) DeepCopyInto(out *GroupMinimum) {
	*out = *in
	if in.Id != nil {
		in, out := &in.Id, &out.Id
		*out = new(string)
		**out = **in
	}
	if in.Issued != nil {
		in, out := &in.Issued, &out.Issued
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GroupMinimum.
func (in *GroupMinimum) DeepCopy() *GroupMinimum {
	if in == nil {
		return nil
	}
	out := new(GroupMinimum)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Nameserver) DeepCopyInto(out *Nameserver) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Nameserver.
func (in *Nameserver) DeepCopy() *Nameserver {
	if in == nil {
		return nil
	}
	out := new(Nameserver)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NbAccessToken) DeepCopyInto(out *NbAccessToken) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NbAccessToken.
func (in *NbAccessToken) DeepCopy() *NbAccessToken {
	if in == nil {
		return nil
	}
	out := new(NbAccessToken)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NbAccessToken) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NbAccessTokenList) DeepCopyInto(out *NbAccessTokenList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NbAccessToken, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NbAccessTokenList.
func (in *NbAccessTokenList) DeepCopy() *NbAccessTokenList {
	if in == nil {
		return nil
	}
	out := new(NbAccessTokenList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NbAccessTokenList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NbAccessTokenObservation) DeepCopyInto(out *NbAccessTokenObservation) {
	*out = *in
	if in.LastUsed != nil {
		in, out := &in.LastUsed, &out.LastUsed
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NbAccessTokenObservation.
func (in *NbAccessTokenObservation) DeepCopy() *NbAccessTokenObservation {
	if in == nil {
		return nil
	}
	out := new(NbAccessTokenObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NbAccessTokenParameters) DeepCopyInto(out *NbAccessTokenParameters) {
	*out = *in
	if in.UserName != nil {
		in, out := &in.UserName, &out.UserName
		*out = new(string)
		**out = **in
	}
	if in.UserId != nil {
		in, out := &in.UserId, &out.UserId
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NbAccessTokenParameters.
func (in *NbAccessTokenParameters) DeepCopy() *NbAccessTokenParameters {
	if in == nil {
		return nil
	}
	out := new(NbAccessTokenParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NbAccessTokenSpec) DeepCopyInto(out *NbAccessTokenSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NbAccessTokenSpec.
func (in *NbAccessTokenSpec) DeepCopy() *NbAccessTokenSpec {
	if in == nil {
		return nil
	}
	out := new(NbAccessTokenSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NbAccessTokenStatus) DeepCopyInto(out *NbAccessTokenStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NbAccessTokenStatus.
func (in *NbAccessTokenStatus) DeepCopy() *NbAccessTokenStatus {
	if in == nil {
		return nil
	}
	out := new(NbAccessTokenStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NbAccount) DeepCopyInto(out *NbAccount) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NbAccount.
func (in *NbAccount) DeepCopy() *NbAccount {
	if in == nil {
		return nil
	}
	out := new(NbAccount)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NbAccount) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NbAccountList) DeepCopyInto(out *NbAccountList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NbAccount, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NbAccountList.
func (in *NbAccountList) DeepCopy() *NbAccountList {
	if in == nil {
		return nil
	}
	out := new(NbAccountList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NbAccountList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NbAccountObservation) DeepCopyInto(out *NbAccountObservation) {
	*out = *in
	in.Settings.DeepCopyInto(&out.Settings)
	if in.UserList != nil {
		in, out := &in.UserList, &out.UserList
		*out = make([]NbAccountUser, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NbAccountObservation.
func (in *NbAccountObservation) DeepCopy() *NbAccountObservation {
	if in == nil {
		return nil
	}
	out := new(NbAccountObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NbAccountParameters) DeepCopyInto(out *NbAccountParameters) {
	*out = *in
	in.Settings.DeepCopyInto(&out.Settings)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NbAccountParameters.
func (in *NbAccountParameters) DeepCopy() *NbAccountParameters {
	if in == nil {
		return nil
	}
	out := new(NbAccountParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NbAccountSpec) DeepCopyInto(out *NbAccountSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NbAccountSpec.
func (in *NbAccountSpec) DeepCopy() *NbAccountSpec {
	if in == nil {
		return nil
	}
	out := new(NbAccountSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NbAccountStatus) DeepCopyInto(out *NbAccountStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NbAccountStatus.
func (in *NbAccountStatus) DeepCopy() *NbAccountStatus {
	if in == nil {
		return nil
	}
	out := new(NbAccountStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NbAccountUser) DeepCopyInto(out *NbAccountUser) {
	*out = *in
	if in.Groups != nil {
		in, out := &in.Groups, &out.Groups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NbAccountUser.
func (in *NbAccountUser) DeepCopy() *NbAccountUser {
	if in == nil {
		return nil
	}
	out := new(NbAccountUser)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NbDnsSetting) DeepCopyInto(out *NbDnsSetting) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NbDnsSetting.
func (in *NbDnsSetting) DeepCopy() *NbDnsSetting {
	if in == nil {
		return nil
	}
	out := new(NbDnsSetting)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NbDnsSetting) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NbDnsSettingList) DeepCopyInto(out *NbDnsSettingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NbDnsSetting, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NbDnsSettingList.
func (in *NbDnsSettingList) DeepCopy() *NbDnsSettingList {
	if in == nil {
		return nil
	}
	out := new(NbDnsSettingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NbDnsSettingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NbDnsSettingObservation) DeepCopyInto(out *NbDnsSettingObservation) {
	*out = *in
	if in.DisabledManagementGroups != nil {
		in, out := &in.DisabledManagementGroups, &out.DisabledManagementGroups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NbDnsSettingObservation.
func (in *NbDnsSettingObservation) DeepCopy() *NbDnsSettingObservation {
	if in == nil {
		return nil
	}
	out := new(NbDnsSettingObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NbDnsSettingParameters) DeepCopyInto(out *NbDnsSettingParameters) {
	*out = *in
	if in.DisabledManagementGroups != nil {
		in, out := &in.DisabledManagementGroups, &out.DisabledManagementGroups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NbDnsSettingParameters.
func (in *NbDnsSettingParameters) DeepCopy() *NbDnsSettingParameters {
	if in == nil {
		return nil
	}
	out := new(NbDnsSettingParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NbDnsSettingSpec) DeepCopyInto(out *NbDnsSettingSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NbDnsSettingSpec.
func (in *NbDnsSettingSpec) DeepCopy() *NbDnsSettingSpec {
	if in == nil {
		return nil
	}
	out := new(NbDnsSettingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NbDnsSettingStatus) DeepCopyInto(out *NbDnsSettingStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NbDnsSettingStatus.
func (in *NbDnsSettingStatus) DeepCopy() *NbDnsSettingStatus {
	if in == nil {
		return nil
	}
	out := new(NbDnsSettingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NbGroup) DeepCopyInto(out *NbGroup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NbGroup.
func (in *NbGroup) DeepCopy() *NbGroup {
	if in == nil {
		return nil
	}
	out := new(NbGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NbGroup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NbGroupList) DeepCopyInto(out *NbGroupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NbGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NbGroupList.
func (in *NbGroupList) DeepCopy() *NbGroupList {
	if in == nil {
		return nil
	}
	out := new(NbGroupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NbGroupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NbGroupObservation) DeepCopyInto(out *NbGroupObservation) {
	*out = *in
	if in.Issued != nil {
		in, out := &in.Issued, &out.Issued
		*out = new(api.GroupIssued)
		**out = **in
	}
	if in.Peers != nil {
		in, out := &in.Peers, &out.Peers
		*out = make([]api.PeerMinimum, len(*in))
		copy(*out, *in)
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make([]api.Resource, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NbGroupObservation.
func (in *NbGroupObservation) DeepCopy() *NbGroupObservation {
	if in == nil {
		return nil
	}
	out := new(NbGroupObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NbGroupParameters) DeepCopyInto(out *NbGroupParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NbGroupParameters.
func (in *NbGroupParameters) DeepCopy() *NbGroupParameters {
	if in == nil {
		return nil
	}
	out := new(NbGroupParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NbGroupSpec) DeepCopyInto(out *NbGroupSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	out.ForProvider = in.ForProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NbGroupSpec.
func (in *NbGroupSpec) DeepCopy() *NbGroupSpec {
	if in == nil {
		return nil
	}
	out := new(NbGroupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NbGroupStatus) DeepCopyInto(out *NbGroupStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NbGroupStatus.
func (in *NbGroupStatus) DeepCopy() *NbGroupStatus {
	if in == nil {
		return nil
	}
	out := new(NbGroupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NbNameServer) DeepCopyInto(out *NbNameServer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NbNameServer.
func (in *NbNameServer) DeepCopy() *NbNameServer {
	if in == nil {
		return nil
	}
	out := new(NbNameServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NbNameServer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NbNameServerList) DeepCopyInto(out *NbNameServerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NbNameServer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NbNameServerList.
func (in *NbNameServerList) DeepCopy() *NbNameServerList {
	if in == nil {
		return nil
	}
	out := new(NbNameServerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NbNameServerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NbNameServerObservation) DeepCopyInto(out *NbNameServerObservation) {
	*out = *in
	if in.Domains != nil {
		in, out := &in.Domains, &out.Domains
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Groups != nil {
		in, out := &in.Groups, &out.Groups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Nameservers != nil {
		in, out := &in.Nameservers, &out.Nameservers
		*out = make([]Nameserver, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NbNameServerObservation.
func (in *NbNameServerObservation) DeepCopy() *NbNameServerObservation {
	if in == nil {
		return nil
	}
	out := new(NbNameServerObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NbNameServerParameters) DeepCopyInto(out *NbNameServerParameters) {
	*out = *in
	if in.Domains != nil {
		in, out := &in.Domains, &out.Domains
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Groups != nil {
		in, out := &in.Groups, &out.Groups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Nameservers != nil {
		in, out := &in.Nameservers, &out.Nameservers
		*out = make([]Nameserver, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NbNameServerParameters.
func (in *NbNameServerParameters) DeepCopy() *NbNameServerParameters {
	if in == nil {
		return nil
	}
	out := new(NbNameServerParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NbNameServerSpec) DeepCopyInto(out *NbNameServerSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NbNameServerSpec.
func (in *NbNameServerSpec) DeepCopy() *NbNameServerSpec {
	if in == nil {
		return nil
	}
	out := new(NbNameServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NbNameServerStatus) DeepCopyInto(out *NbNameServerStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NbNameServerStatus.
func (in *NbNameServerStatus) DeepCopy() *NbNameServerStatus {
	if in == nil {
		return nil
	}
	out := new(NbNameServerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NbNetwork) DeepCopyInto(out *NbNetwork) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NbNetwork.
func (in *NbNetwork) DeepCopy() *NbNetwork {
	if in == nil {
		return nil
	}
	out := new(NbNetwork)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NbNetwork) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NbNetworkList) DeepCopyInto(out *NbNetworkList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NbNetwork, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NbNetworkList.
func (in *NbNetworkList) DeepCopy() *NbNetworkList {
	if in == nil {
		return nil
	}
	out := new(NbNetworkList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NbNetworkList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NbNetworkObservation) DeepCopyInto(out *NbNetworkObservation) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Policies != nil {
		in, out := &in.Policies, &out.Policies
		*out = new([]string)
		if **in != nil {
			in, out := *in, *out
			*out = make([]string, len(*in))
			copy(*out, *in)
		}
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new([]string)
		if **in != nil {
			in, out := *in, *out
			*out = make([]string, len(*in))
			copy(*out, *in)
		}
	}
	if in.Routers != nil {
		in, out := &in.Routers, &out.Routers
		*out = new([]string)
		if **in != nil {
			in, out := *in, *out
			*out = make([]string, len(*in))
			copy(*out, *in)
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NbNetworkObservation.
func (in *NbNetworkObservation) DeepCopy() *NbNetworkObservation {
	if in == nil {
		return nil
	}
	out := new(NbNetworkObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NbNetworkParameters) DeepCopyInto(out *NbNetworkParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NbNetworkParameters.
func (in *NbNetworkParameters) DeepCopy() *NbNetworkParameters {
	if in == nil {
		return nil
	}
	out := new(NbNetworkParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NbNetworkResource) DeepCopyInto(out *NbNetworkResource) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NbNetworkResource.
func (in *NbNetworkResource) DeepCopy() *NbNetworkResource {
	if in == nil {
		return nil
	}
	out := new(NbNetworkResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NbNetworkResource) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NbNetworkResourceList) DeepCopyInto(out *NbNetworkResourceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NbNetworkResource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NbNetworkResourceList.
func (in *NbNetworkResourceList) DeepCopy() *NbNetworkResourceList {
	if in == nil {
		return nil
	}
	out := new(NbNetworkResourceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NbNetworkResourceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NbNetworkResourceObservation) DeepCopyInto(out *NbNetworkResourceObservation) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Groups != nil {
		in, out := &in.Groups, &out.Groups
		*out = new([]GroupMinimum)
		if **in != nil {
			in, out := *in, *out
			*out = make([]GroupMinimum, len(*in))
			for i := range *in {
				(*in)[i].DeepCopyInto(&(*out)[i])
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NbNetworkResourceObservation.
func (in *NbNetworkResourceObservation) DeepCopy() *NbNetworkResourceObservation {
	if in == nil {
		return nil
	}
	out := new(NbNetworkResourceObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NbNetworkResourceParameters) DeepCopyInto(out *NbNetworkResourceParameters) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Groups != nil {
		in, out := &in.Groups, &out.Groups
		*out = new([]GroupMinimum)
		if **in != nil {
			in, out := *in, *out
			*out = make([]GroupMinimum, len(*in))
			for i := range *in {
				(*in)[i].DeepCopyInto(&(*out)[i])
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NbNetworkResourceParameters.
func (in *NbNetworkResourceParameters) DeepCopy() *NbNetworkResourceParameters {
	if in == nil {
		return nil
	}
	out := new(NbNetworkResourceParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NbNetworkResourceSpec) DeepCopyInto(out *NbNetworkResourceSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NbNetworkResourceSpec.
func (in *NbNetworkResourceSpec) DeepCopy() *NbNetworkResourceSpec {
	if in == nil {
		return nil
	}
	out := new(NbNetworkResourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NbNetworkResourceStatus) DeepCopyInto(out *NbNetworkResourceStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NbNetworkResourceStatus.
func (in *NbNetworkResourceStatus) DeepCopy() *NbNetworkResourceStatus {
	if in == nil {
		return nil
	}
	out := new(NbNetworkResourceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NbNetworkRouter) DeepCopyInto(out *NbNetworkRouter) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NbNetworkRouter.
func (in *NbNetworkRouter) DeepCopy() *NbNetworkRouter {
	if in == nil {
		return nil
	}
	out := new(NbNetworkRouter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NbNetworkRouter) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NbNetworkRouterList) DeepCopyInto(out *NbNetworkRouterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NbNetworkRouter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NbNetworkRouterList.
func (in *NbNetworkRouterList) DeepCopy() *NbNetworkRouterList {
	if in == nil {
		return nil
	}
	out := new(NbNetworkRouterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NbNetworkRouterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NbNetworkRouterObservation) DeepCopyInto(out *NbNetworkRouterObservation) {
	*out = *in
	if in.Peer != nil {
		in, out := &in.Peer, &out.Peer
		*out = new(string)
		**out = **in
	}
	if in.PeerGroup != nil {
		in, out := &in.PeerGroup, &out.PeerGroup
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NbNetworkRouterObservation.
func (in *NbNetworkRouterObservation) DeepCopy() *NbNetworkRouterObservation {
	if in == nil {
		return nil
	}
	out := new(NbNetworkRouterObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NbNetworkRouterParameters) DeepCopyInto(out *NbNetworkRouterParameters) {
	*out = *in
	if in.Peer != nil {
		in, out := &in.Peer, &out.Peer
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NbNetworkRouterParameters.
func (in *NbNetworkRouterParameters) DeepCopy() *NbNetworkRouterParameters {
	if in == nil {
		return nil
	}
	out := new(NbNetworkRouterParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NbNetworkRouterSpec) DeepCopyInto(out *NbNetworkRouterSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NbNetworkRouterSpec.
func (in *NbNetworkRouterSpec) DeepCopy() *NbNetworkRouterSpec {
	if in == nil {
		return nil
	}
	out := new(NbNetworkRouterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NbNetworkRouterStatus) DeepCopyInto(out *NbNetworkRouterStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NbNetworkRouterStatus.
func (in *NbNetworkRouterStatus) DeepCopy() *NbNetworkRouterStatus {
	if in == nil {
		return nil
	}
	out := new(NbNetworkRouterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NbNetworkSpec) DeepCopyInto(out *NbNetworkSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	out.ForProvider = in.ForProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NbNetworkSpec.
func (in *NbNetworkSpec) DeepCopy() *NbNetworkSpec {
	if in == nil {
		return nil
	}
	out := new(NbNetworkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NbNetworkStatus) DeepCopyInto(out *NbNetworkStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NbNetworkStatus.
func (in *NbNetworkStatus) DeepCopy() *NbNetworkStatus {
	if in == nil {
		return nil
	}
	out := new(NbNetworkStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NbPolicy) DeepCopyInto(out *NbPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NbPolicy.
func (in *NbPolicy) DeepCopy() *NbPolicy {
	if in == nil {
		return nil
	}
	out := new(NbPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NbPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NbPolicyList) DeepCopyInto(out *NbPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NbPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NbPolicyList.
func (in *NbPolicyList) DeepCopy() *NbPolicyList {
	if in == nil {
		return nil
	}
	out := new(NbPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NbPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NbPolicyObservation) DeepCopyInto(out *NbPolicyObservation) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Id != nil {
		in, out := &in.Id, &out.Id
		*out = new(string)
		**out = **in
	}
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = new([]PolicyRule)
		if **in != nil {
			in, out := *in, *out
			*out = make([]PolicyRule, len(*in))
			for i := range *in {
				(*in)[i].DeepCopyInto(&(*out)[i])
			}
		}
	}
	if in.SourcePostureChecks != nil {
		in, out := &in.SourcePostureChecks, &out.SourcePostureChecks
		*out = new([]string)
		if **in != nil {
			in, out := *in, *out
			*out = make([]string, len(*in))
			copy(*out, *in)
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NbPolicyObservation.
func (in *NbPolicyObservation) DeepCopy() *NbPolicyObservation {
	if in == nil {
		return nil
	}
	out := new(NbPolicyObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NbPolicyParameters) DeepCopyInto(out *NbPolicyParameters) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]PolicyRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SourcePostureChecks != nil {
		in, out := &in.SourcePostureChecks, &out.SourcePostureChecks
		*out = new([]string)
		if **in != nil {
			in, out := *in, *out
			*out = make([]string, len(*in))
			copy(*out, *in)
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NbPolicyParameters.
func (in *NbPolicyParameters) DeepCopy() *NbPolicyParameters {
	if in == nil {
		return nil
	}
	out := new(NbPolicyParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NbPolicySpec) DeepCopyInto(out *NbPolicySpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NbPolicySpec.
func (in *NbPolicySpec) DeepCopy() *NbPolicySpec {
	if in == nil {
		return nil
	}
	out := new(NbPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NbPolicyStatus) DeepCopyInto(out *NbPolicyStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NbPolicyStatus.
func (in *NbPolicyStatus) DeepCopy() *NbPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(NbPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NbSetupKey) DeepCopyInto(out *NbSetupKey) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NbSetupKey.
func (in *NbSetupKey) DeepCopy() *NbSetupKey {
	if in == nil {
		return nil
	}
	out := new(NbSetupKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NbSetupKey) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NbSetupKeyList) DeepCopyInto(out *NbSetupKeyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NbSetupKey, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NbSetupKeyList.
func (in *NbSetupKeyList) DeepCopy() *NbSetupKeyList {
	if in == nil {
		return nil
	}
	out := new(NbSetupKeyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NbSetupKeyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NbSetupKeyObservation) DeepCopyInto(out *NbSetupKeyObservation) {
	*out = *in
	if in.AutoGroups != nil {
		in, out := &in.AutoGroups, &out.AutoGroups
		*out = new([]string)
		if **in != nil {
			in, out := *in, *out
			*out = make([]string, len(*in))
			copy(*out, *in)
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NbSetupKeyObservation.
func (in *NbSetupKeyObservation) DeepCopy() *NbSetupKeyObservation {
	if in == nil {
		return nil
	}
	out := new(NbSetupKeyObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NbSetupKeyParameters) DeepCopyInto(out *NbSetupKeyParameters) {
	*out = *in
	if in.AutoGroups != nil {
		in, out := &in.AutoGroups, &out.AutoGroups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NbSetupKeyParameters.
func (in *NbSetupKeyParameters) DeepCopy() *NbSetupKeyParameters {
	if in == nil {
		return nil
	}
	out := new(NbSetupKeyParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NbSetupKeySpec) DeepCopyInto(out *NbSetupKeySpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NbSetupKeySpec.
func (in *NbSetupKeySpec) DeepCopy() *NbSetupKeySpec {
	if in == nil {
		return nil
	}
	out := new(NbSetupKeySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NbSetupKeyStatus) DeepCopyInto(out *NbSetupKeyStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NbSetupKeyStatus.
func (in *NbSetupKeyStatus) DeepCopy() *NbSetupKeyStatus {
	if in == nil {
		return nil
	}
	out := new(NbSetupKeyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NbUser) DeepCopyInto(out *NbUser) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NbUser.
func (in *NbUser) DeepCopy() *NbUser {
	if in == nil {
		return nil
	}
	out := new(NbUser)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NbUser) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NbUserList) DeepCopyInto(out *NbUserList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NbUser, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NbUserList.
func (in *NbUserList) DeepCopy() *NbUserList {
	if in == nil {
		return nil
	}
	out := new(NbUserList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NbUserList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NbUserObservation) DeepCopyInto(out *NbUserObservation) {
	*out = *in
	if in.AutoGroups != nil {
		in, out := &in.AutoGroups, &out.AutoGroups
		*out = new([]string)
		if **in != nil {
			in, out := *in, *out
			*out = make([]string, len(*in))
			copy(*out, *in)
		}
	}
	if in.IsCurrent != nil {
		in, out := &in.IsCurrent, &out.IsCurrent
		*out = new(bool)
		**out = **in
	}
	if in.IsServiceUser != nil {
		in, out := &in.IsServiceUser, &out.IsServiceUser
		*out = new(bool)
		**out = **in
	}
	if in.Issued != nil {
		in, out := &in.Issued, &out.Issued
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NbUserObservation.
func (in *NbUserObservation) DeepCopy() *NbUserObservation {
	if in == nil {
		return nil
	}
	out := new(NbUserObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NbUserParameters) DeepCopyInto(out *NbUserParameters) {
	*out = *in
	if in.IsServiceUser != nil {
		in, out := &in.IsServiceUser, &out.IsServiceUser
		*out = new(bool)
		**out = **in
	}
	if in.AutoGroups != nil {
		in, out := &in.AutoGroups, &out.AutoGroups
		*out = new([]string)
		if **in != nil {
			in, out := *in, *out
			*out = make([]string, len(*in))
			copy(*out, *in)
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NbUserParameters.
func (in *NbUserParameters) DeepCopy() *NbUserParameters {
	if in == nil {
		return nil
	}
	out := new(NbUserParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NbUserSpec) DeepCopyInto(out *NbUserSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NbUserSpec.
func (in *NbUserSpec) DeepCopy() *NbUserSpec {
	if in == nil {
		return nil
	}
	out := new(NbUserSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NbUserStatus) DeepCopyInto(out *NbUserStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NbUserStatus.
func (in *NbUserStatus) DeepCopy() *NbUserStatus {
	if in == nil {
		return nil
	}
	out := new(NbUserStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyRule) DeepCopyInto(out *PolicyRule) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.DestinationResourceName != nil {
		in, out := &in.DestinationResourceName, &out.DestinationResourceName
		*out = new(string)
		**out = **in
	}
	if in.Destinations != nil {
		in, out := &in.Destinations, &out.Destinations
		*out = new([]GroupMinimum)
		if **in != nil {
			in, out := *in, *out
			*out = make([]GroupMinimum, len(*in))
			for i := range *in {
				(*in)[i].DeepCopyInto(&(*out)[i])
			}
		}
	}
	if in.Id != nil {
		in, out := &in.Id, &out.Id
		*out = new(string)
		**out = **in
	}
	if in.PortRanges != nil {
		in, out := &in.PortRanges, &out.PortRanges
		*out = new([]RulePortRange)
		if **in != nil {
			in, out := *in, *out
			*out = make([]RulePortRange, len(*in))
			copy(*out, *in)
		}
	}
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = new([]string)
		if **in != nil {
			in, out := *in, *out
			*out = make([]string, len(*in))
			copy(*out, *in)
		}
	}
	if in.SourceResourceName != nil {
		in, out := &in.SourceResourceName, &out.SourceResourceName
		*out = new(string)
		**out = **in
	}
	if in.Sources != nil {
		in, out := &in.Sources, &out.Sources
		*out = new([]GroupMinimum)
		if **in != nil {
			in, out := *in, *out
			*out = make([]GroupMinimum, len(*in))
			for i := range *in {
				(*in)[i].DeepCopyInto(&(*out)[i])
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyRule.
func (in *PolicyRule) DeepCopy() *PolicyRule {
	if in == nil {
		return nil
	}
	out := new(PolicyRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RulePortRange) DeepCopyInto(out *RulePortRange) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RulePortRange.
func (in *RulePortRange) DeepCopy() *RulePortRange {
	if in == nil {
		return nil
	}
	out := new(RulePortRange)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserPermissions) DeepCopyInto(out *UserPermissions) {
	*out = *in
	if in.DashboardView != nil {
		in, out := &in.DashboardView, &out.DashboardView
		*out = new(UserPermissionsDashboardView)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserPermissions.
func (in *UserPermissions) DeepCopy() *UserPermissions {
	if in == nil {
		return nil
	}
	out := new(UserPermissions)
	in.DeepCopyInto(out)
	return out
}
